### creates a new auction
POST {{host}}:{{port}}/api/auctions/
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "userid":0,
  "title": "",
  "description": "",
  "duration":0,
  "startingbid":0,
  "MaxBid":0

}
### get all auction
GET {{host}}:{{port}}/api/auctions
Accept: application/json
### get auction by ID
GET {{host}}:{{port}}/api/auctions/{id}
Accept: application/json
### deletes auction based on id
DELETE {{host}}:{{port}}/api/auctions/{id}
Accept: application/json

> {%
client.test(
    "auction deleted",
    function() {
        client.assert(response.status === 200, "Response status is not 200 ");

    }
);
%}
### update auction info
PATCH {{host}}:{{port}}/api/auctions/{id}
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "userid":0,
  "title": "",
  "description": "",
  "duration":0,
  "startingbid":0,
  "MaxBid":0
}